# -*- coding: utf-8 -*-
"""belajar-gradio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bBfeuJyM7BaB2LfMcvBbFx80YZusFE9n
"""

# Belajar Gradio
# Willi

# Import library
!pip install gradio

# Import library tambahan
import gradio as gr
import requests as rq

def halo(namo):
  return "Halo, nama saya " + namo + "!"

demo = gr.Interface(fn=halo, inputs="text", outputs="text")

demo.launch()